name: Build

on:
  pull_request:
    branches:
      - master
  push:
  release:

jobs:
  build:
    name: ${{ matrix.arch }} build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_cortex-a53


    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare package
        run: |
          sed -i '/^SRCDIR/ s/$/\/feed/' openwrt/Makefile
          mkdir -p feed/scutclient
          mv openwrt/Makefile feed/scutclient/
          cat feed/scutclient/Makefile

      - name: Build
        uses: openwrt/gh-action-sdk@v7 # 使用较新的版本尝试兼容
        env:
          ARCH: aarch64_cortex-a53
          FEEDNAME: action
          PACKAGES: scutclient
          V: s  # 强制开启详细日志，这样下次报错我们能看到具体哪行代码错了

      - name: Check Build Result
        run: ls -R bin/ # 这一步能让我们在日志里确认 ipk 到底生成在哪个文件夹了

      - name: Store packages
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}-packages
          path: bin/packages/${{ matrix.arch }}/action/*.ipk
